### ISSUE TITLE
Testing Issues Checklist - Website Rebuild

### ISSUE THREAD

**Issue by jermyk** [thelawcentresnetwork/lcn-design-system#80]

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/11

Need a steer on this one?

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/11

AC - On hover, the navigation drop down displays using styles matching the referenced designs
Actual - Dropdown only displays if user clicks on it


![Image](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/dfdca544-7f94-42f6-86e4-cacfcfbb0236)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/11

Unable to log in to the contentful account?



![Image](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/b3e25320-5ff9-401d-9326-6835d19b13e1)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/11

- [x] When active the visible navigation menu matches the referenced designs 
![LCN - Mobile - Active menu](https://github.com/thelawcentresnetwork/lcn_website/assets/4446325/dc1ee56c-e7b8-461d-9c8c-bcab03ad581f)
@rosejbon  The mobile menu dropdown differs in colour to the desktop version?

**Comment by rosejbon** [comment]
> 

Yeah we didn't have any designs so have done this as an "mvp" mobile for now.

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/10

- [ ] There is a footer at the bottom of every page
There is no https://lcn-staging.vercel.app/law-centres-join-call-for-nationwide-rent-freeze

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/10
News is in the header twice


![Image](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/d5caba34-914d-4479-998c-f18b37c63c7a)

**Comment by jermyk** [comment]
Phone favicon is differnet to desktop

![Image](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/fac49996-f711-436e-a775-a757101c79fd)

**Comment by jermyk** [comment]
Where did this come from?

![Image](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/5eb6e39c-0407-4d6a-9f00-fdbd4998bef3)

**Comment by jermyk** [comment]
**Copy overlapping buttons**
![Screenshot_073123_031049_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/dbe602e9-5286-48fb-bbf1-a9418a3fb257)

**Comment by jermyk** [comment]
**Responsiveness on android phone**
![Screenshot_080223_113751_AM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/dfa97483-8250-42fb-ac67-22290db92376)

**Comment by jermyk** [comment]
**api error**

![Screenshot_080223_120021_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/0c963ec4-bb62-4099-abcc-756868b7c760)

**Comment by jermyk** [comment]
**Check callout boxes for responsiveness**
![Screenshot_080223_015628_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/de09b8e7-c74d-486a-8a0a-90c146936e0f)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/5

- [ ] There exists a component named Component: [Section](https://app.contentful.com/spaces/y26owwfe9yxn/environments/master/entries/41fH5iRdkZrFWApBNbCDTC?previousEntries=2EKAyB7SNtHCyKsqN1EWEZ) in contentful

![Screenshot_080223_023403_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/007f0159-594a-4f39-a62d-6c8af8f3455e)
![Untitled_Clipping_080223_023524_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/b672285f-21af-4f27-9af6-b1213cb7babf)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/5
- [ ]This component can be added to Page:General

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-design-system/issues/49

- [ ] The design is responsive and wraps as the screen sizes decreases Unable to see this on the site?

**Comment by jermyk** [comment]
**Bug**
Application error: a client-side exception has occurred (see the browser console for more information). displays when button is fired.

![Screenshot_080423_105236_AM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/449d320f-e227-48fe-bbc2-85686cad14ac)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/4

Need a steer on some of the AC
Also where does the rich text display on the website?

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/8

Need a steer on 
 This component can be added to Page: General but not Component: Grid, Component: Section

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/22

The component can be added to a Page: General and a Page: Simple

**Comment by jermyk** [comment]
https://github.com/orgs/thelawcentresnetwork/projects/7/views/1?pane=issue&itemId=31015086


https://lcn-staging.vercel.app/news

![Screenshot_080423_045104_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/ee7d706d-8751-44b8-a6c8-c317aff54c1e)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/50

Adding news atricles.
User added articles by duplicating pages in contentful eg 12,13,14,15, each of the new page appearing on the 1st page.
When article 16 was added, it displayed on page 2 and article seven was the displaying as the latest article.

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/50

Adding news atricles.
User added articles by duplicating pages in contentful eg 12,13,14,15, each of the new page appearing on the 1st page.
When article 16 was added, it displayed on page 2 and article seven was the displaying as the latest article.

**Comment by jermyk** [comment]
News articles out of alignment?
![Screenshot_080723_014756_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/80b69258-6628-407d-88d3-11bb056ae50c)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/15

Check hero image v article image?
https://lcn-staging.vercel.app/news/news-article-eight

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn_website/issues/41

Need to share on SM

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/2

Need to test against a post code area where there are no law centres?

**Comment by jermyk** [comment]
Error when creating https://github.com/thelawcentresnetwork/lcn-jamstack-utilities/issues/37

![Screenshot_080723_033213_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/46f1977e-6f58-4d9f-95dc-61450c7a18cc)

**Comment by jermyk** [comment]
Timestamp
![Screenshot_080723_033632_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/f9f081fd-026a-4f4b-afb9-0b34be7488be)

**Comment by jermyk** [comment]
88Time added and UTC+00:00 changed and "Z" appears?
![Screenshot_080723_034104_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/a0c31f68-5821-473a-8da0-21e175087ae9)

**Comment by jermyk** [comment]
**Support us section**

Call to action text displaying as overlapping
![Screenshot_081023_110138_AM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/cfba57c3-b66e-4eb1-8f50-13415ec0e98a)

**Comment by jermyk** [comment]
**Newsletter sign 400 error**
![Screenshot_081023_021806_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/455247fc-197c-4c8c-85ba-ff5639da75c8)

**Comment by jermyk** [comment]
https://github.com/thelawcentresnetwork/lcn-design-system/issues/160
@hannahouazzane I checked this on android too, and it still displays as not wrapping (works on the iPhone SE (simulator) and I've asked Max to check on his device.
![Screenshot_081023_024612_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/e4f13819-20e1-4f61-960a-306d130e817a)

**Comment by jermyk** [comment]
**News page doesn't scroll to top of the page when paginating**
@rosejbon 
When a user is navving the news page using the previous/next buttons the page doesn't scroll to the top and requires manual intervention (in fact on page three the user is looking at the footer)
![Screenshot_081023_030127_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/3882756d-f4c1-405b-83a1-79718d461700)

![Screenshot_081023_030216_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/45e1c35d-4d34-4f61-9057-0ddded04c0e0)

**Comment by jermyk** [comment]
@rosejbon 
Should "Who are we" have a question mark?
![Screenshot_081023_031236_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/fe7efb5a-62f8-4a0e-882b-b6e9bbda7600)

**Comment by jermyk** [comment]
**Homepage image (on a monitor) overlaps LCN logo**

![Screenshot_081023_033033_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/cda913da-754d-4173-a6f3-a323373eb4de)

**Comment by jermyk** [comment]
** A few oddities on the https://lcn-staging.vercel.app/test-page1**

![Screenshot_081023_033640_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/91e4b7a0-3f1a-4bd6-8d33-eefa1576c924)
![Screenshot_081023_033721_PM](https://github.com/thelawcentresnetwork/lcn-design-system/assets/4446325/771bbf22-1b94-464b-8ee0-07ccc96f07dd)
